<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2018 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------

// 事件定义文件

use app\domain\user\event\DiamondExchangeBeanDomainEvent;
use app\event\GhAuditMemberEvent;
use app\event\InnerAuditMemberEvent;
use app\event\InnerRoomPartyEvent;
use app\event\UserCancelEvent;

return [
    'bind' => [
        'SendGiftDomainEvent' => 'app\domain\gift\event\SendGiftDomainEvent',
        'ReceiveGiftDomainEvent' => 'app\domain\gift\event\ReceiveGiftDomainEvent',
        'OpenGiftDomainEvent' => 'app\domain\gift\event\OpenGiftDomainEvent',
        'UserLoginDomainEvent' => 'app\domain\user\event\UserLoginDomainEvent',
        'UserInfoSaveDomainEvent' => 'app\domain\user\event\UserInfoSaveDomainEvent',
        'CompleteRealUserDomainEvent' => 'app\domain\events\CompleteRealUserDomainEvent',
        'CompleteNewerTaskDomainEvent' => 'app\domain\events\CompleteNewerTaskDomainEvent',
        'UserUpdateProfileDomainEvent' => 'app\domain\events\UserUpdateProfileDomainEvent',
        'PerfectUserInfoEvent' => 'app\domain\user\event\PerfectUserInfoEvent',
        'FocusFriendDomainEvent' => 'app\domain\events\FocusFriendDomainEvent',
        'BindMobileDomainEvent' => 'app\domain\events\BindMobileDomainEvent',
        'BuyGoodsEvent' => 'app\event\BuyGoodsEvent',
        'SendGiftEvent' => 'app\event\SendGiftEvent',
        'BreakBoxEvent' => 'app\event\BreakBoxEvent',
        'BreakBoxNewEvent' => 'app\event\BreakBoxNewEvent',
        'TurntableEvent' => 'app\event\TurntableEvent',
        'RoomLockEvent' => 'app\event\RoomLockEvent',
        'RoomUnlockEvent' => 'app\event\RoomUnlockEvent',
        'RoomUpdateEvent' => 'app\event\RoomUpdateEvent',
        'RoomAttentionEvent' => 'app\event\RoomAttentionEvent',
        'RoomCreateEvent' => 'app\event\RoomCreateEvent',
        'RoomShareEvent' => 'app\event\RoomShareEvent',
        'RoomStaySecondEvent' => 'app\event\RoomStaySecondEvent',
        'UserLoginEvent' => 'app\event\UserLoginEvent',
        'UserRegisterEvent' => 'app\event\UserRegisterEvent',
        'AndroidActivateEvent' => 'app\event\AndroidActivateEvent',
        'ReleaseDynamicEvent' => 'app\event\ReleaseDynamicEvent',
        'PrivateChatEvent' => 'app\event\PrivateChatEvent',
        'DukeLevelChangeEvent' => 'app\event\DukeLevelChangeEvent',
        'LevelChangeEvent' => 'app\event\LevelChangeEvent',
        'TaoJinRewardEvent' => 'app\event\TaoJinRewardEvent',
        'OreExchangeEvent' => 'app\event\OreExchangeEvent',
        'BuyVipEvent' => 'app\event\BuyVipEvent',
        'VipExpiresEvent' => 'app\event\VipExpiresEvent',
        'VipWillExpiresEvent' => 'app\event\VipWillExpiresEvent',
        'RoomBanUserEvent' => 'app\event\RoomBanUserEvent',
        'RoomBlackUserEvent' => 'app\event\RoomBlackUserEvent',
        'SendRedPacketEvent' => 'app\event\SendRedPacketEvent',
        'UserUpdateProfileEvent' => 'app\event\UserUpdateProfileEvent',
        'MemberDetailAuditEvent' => 'app\event\MemberDetailAuditEvent',
        'RoomManagerAddEvent' => 'app\event\RoomManagerAddEvent',
        'RoomManagerRemoveEvent' => 'app\event\RoomManagerRemoveEvent',
        'PropTypeActionEvent' => 'app\event\PropTypeActionEvent',
        'VisitUserInfoEvent' => 'app\event\VisitUserInfoEvent',
        'ThreeLootNoticeEvent' => 'app\event\ThreeLootNoticeEvent',
        'ChargeEvent' => 'app\event\ChargeEvent',
        'IosChargeEvent' => 'app\event\IosChargeEvent',
        'ReduEvent' => 'app\event\ReduEvent',
        'VisitEvent' => 'app\event\VisitEvent',
        'CallListEvent' => 'app\event\CallListEvent',
        'UserGreetEvent' => 'app\event\UserGreetEvent',
        'CareUserListEvent' => 'app\event\CareUserListEvent',
        'EnjoyForumEvent' => 'app\event\EnjoyForumEvent',
        'ReplyForumEvent'=>'app\event\ReplyForumEvent',
        'ForumDetailEvent' => 'app\event\ForumDetailEvent',
        'TaskRewardDomianEvent' => 'app\domain\events\TaskRewardDomianEvent',
        'TaskFinishedDomianEvent' => 'app\domain\events\TaskFinishedDomianEvent',
        'ImReplyListEvent' => 'app\event\ImReplyListEvent',
        'TradeUnionAgentEvent' => 'app\event\TradeUnionAgentEvent',
        'TeenHandler' => 'app\domain\user\event\handler\TeenHandler',
        'ForumCheckPassEvent' => 'app\event\ForumCheckPassEvent',
        'ImChatPointEvent' => 'app\event\ImChatPointEvent',
        'RoomInfoUpdateNoticeEvent' => 'app\event\RoomInfoUpdateNoticeEvent',
        'GhAuditMemberEvent' => 'app\event\GhAuditMemberEvent',
        'InnerAuditMemberEvent' => 'app\event\InnerAuditMemberEvent',
        'InnerRoomPartyEvent' => 'app\event\InnerRoomPartyEvent',
        'UserInfoUpdateNoticeEvent' => 'app\event\UserInfoUpdateNoticeEvent',
        'GetTaskRewardEvent'=>'app\event\GetTaskRewardEvent',
        'BeanExchangeCoinDomainEvent'=>'app\domain\user\event\BeanExchangeCoinDomainEvent',
        'DoLotteryEvent'=>'app\event\DoLotteryEvent',
        'DiamondExchangeBeanDomainEvent' => 'app\domain\user\event\DiamondExchangeBeanDomainEvent',
        'UserUpdateMobileEvent'=>'app\event\UserUpdateMobileEvent',
        'UserTaskWeekSignEvent'=>'app\event\UserTaskWeekSignEvent',
        'SwitchMonitorEvent'=>'app\event\SwitchMonitorEvent',
        'UserCancelEvent'=>'app\event\UserCancelEvent',
        'AttentionUserEvent'=>'app\event\AttentionUserEvent',
    ],

    'listen' => [
        'AppInit' => [],
        'HttpRun' => [],
        'HttpEnd' => [],
        'LogLevel' => [],
        'LogWrite' => [],
    ],

    'subscribe' => [
        'app\event\handler\AppMsgHandler',
        'app\event\handler\DukeHandler',
        'app\event\handler\VipHandler',
        'app\domain\rank\event\handler\RankEventHandler',
        'app\domain\level\event\handler\LevelEventHandler',
        'app\domain\mall\event\handler\MallEventHandler',
        'app\domain\gift\event\handler\GiftEventHandler',
        'app\domain\task\event\handler\TaskDomainEventHandler',
        'app\domain\task\event\handler\TaskEventHandler',
        'app\domain\game\event\handler\GameEventHandler',
        'app\domain\led\event\handler\LedEventHandler',
        'app\domain\activity\event\handler\QixiEventHandler',
        'app\event\handler\RoomHandler',
        'app\event\handler\RoomNotifyHandler',
        'app\domain\promote\event\handler\PromoteHandler',
        'app\event\handler\YunxinHandler',
        'app\domain\user\event\UserEventHandler',
        'app\event\handler\UserCacheHandler',
        'app\event\handler\RankHandler',
        'app\event\handler\RedPacketHandler',
        'app\domain\reddot\event\handler\RedDotHandler',
        'app\domain\user\event\handler\TeenHandler',
        'app\domain\activity\event\handler\ActivityEventHandler',
        'app\domain\activity\event\handler\SpringFestivalEventHandler',
        'app\domain\activity\event\handler\RecallDomainHandler',
        'app\domain\census\event\handler\CensusEventHandler',
        'app\domain\im\event\handler\ImChatPointEventHandler',
        'app\domain\im\event\handler\ImChatPointHandler',
//        'app\event\handler\ElasticSyncPublishHandler',
//        'app\event\handler\SensorsDataHandler',
//        'app\domain\specialcare\event\handler\SpecialCareHandler',
        'app\domain\elastic\event\handler\ElasticSyncConsumerHandler',
        'app\domain\forum\event\handler\ForumHandler',
        'app\domain\user\event\handler\UserRemarkNameHandler',
        'app\domain\user\event\handler\UserHiddenHandler',
        'app\domain\imresource\event\handler\ImBackgroundHandler',
        'app\domain\imresource\event\handler\ImBubbleHandler',
        'app\domain\imresource\event\handler\ImEmotionHandler',
        'app\domain\pay\event\handler\FirstChargeHandler',
    ],
];
